# Generated by Django 3.1.2 on 2020-11-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento_user',
            name='TipoEvento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='Probabilidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Frecuencia'),
        ),
    ]
