# Generated by Django 3.1.2 on 2020-10-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Frecuencia', models.IntegerField()),
                ('Probabilidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Probabilidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Intereses', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEvento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPregunta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPrestamo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroTurnos', models.IntegerField()),
                ('Felicidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('DineroEfectivo', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Ingresos', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Egresos', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(max_length=10)),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.evento')),
                ('Preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.preguntas')),
                ('Prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='Prueba2',
        ),
        migrations.AddField(
            model_name='turnos',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.user'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='TipoPrestamo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.tipo_prestamo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.user'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='TipoPregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.tipo_pregunta'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.user'),
        ),
        migrations.AddField(
            model_name='evento',
            name='TipoEvento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.tipo_evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.user'),
        ),
    ]
