# Generated by Django 3.1.2 on 2020-11-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0002_auto_20201111_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_user',
            name='TipoEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.tipoevento'),
        ),
    ]
