# Generated by Django 3.0.7 on 2020-10-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0002_auto_20200928_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Afecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Afecta')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos_Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Afecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Afecta')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos_Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Requisitos')),
            ],
        ),
        migrations.RenameField(
            model_name='evento_requisitos',
            old_name='id_Evento',
            new_name='Evento',
        ),
        migrations.RenameField(
            model_name='evento_requisitos',
            old_name='id_Requisito',
            new_name='Requisito',
        ),
        migrations.RenameField(
            model_name='preguntas_afecta',
            old_name='id_Afecta',
            new_name='Afecta',
        ),
        migrations.RenameField(
            model_name='preguntas_afecta',
            old_name='id_Preguntas',
            new_name='Preguntas',
        ),
        migrations.RenameField(
            model_name='preguntas_requisitos',
            old_name='id_Preguntas',
            new_name='Preguntas',
        ),
        migrations.RenameField(
            model_name='preguntas_requisitos',
            old_name='id_Requisito',
            new_name='Requisito',
        ),
        migrations.RenameField(
            model_name='prestamo_afect',
            old_name='id_Afecta',
            new_name='Afecta',
        ),
        migrations.RenameField(
            model_name='prestamo_afect',
            old_name='id_Prestamo',
            new_name='Prestamo',
        ),
        migrations.RenameField(
            model_name='prestamo_requisitos',
            old_name='id_Prestamo',
            new_name='Prestamo',
        ),
        migrations.RenameField(
            model_name='prestamo_requisitos',
            old_name='id_Requisito',
            new_name='Requisito',
        ),
        migrations.AlterField(
            model_name='evento',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='Afecta',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='Requisitos',
        ),
        migrations.AlterField(
            model_name='turnos',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
        migrations.AlterUniqueTogether(
            name='evento_requisitos',
            unique_together={('Requisito', 'Evento')},
        ),
        migrations.AlterUniqueTogether(
            name='preguntas_afecta',
            unique_together={('Afecta', 'Preguntas')},
        ),
        migrations.AlterUniqueTogether(
            name='preguntas_requisitos',
            unique_together={('Requisito', 'Preguntas')},
        ),
        migrations.AlterUniqueTogether(
            name='prestamo_afect',
            unique_together={('Afecta', 'Prestamo')},
        ),
        migrations.AlterUniqueTogether(
            name='prestamo_requisitos',
            unique_together={('Requisito', 'Prestamo')},
        ),
        migrations.DeleteModel(
            name='Evento_Afect',
        ),
        migrations.AddField(
            model_name='turnos_requisitos',
            name='Turnos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Turnos'),
        ),
        migrations.AddField(
            model_name='turnos_afecta',
            name='Turnos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Turnos'),
        ),
        migrations.AddField(
            model_name='evento_afecta',
            name='Evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='Afecta',
            field=models.ManyToManyField(through='monyLifeApp.Evento_Afecta', to='monyLifeApp.Afecta'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='Afecta',
            field=models.ManyToManyField(through='monyLifeApp.Turnos_Afecta', to='monyLifeApp.Afecta'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='Requisitos',
            field=models.ManyToManyField(through='monyLifeApp.Turnos_Requisitos', to='monyLifeApp.Requisitos'),
        ),
        migrations.AlterUniqueTogether(
            name='turnos_requisitos',
            unique_together={('Requisito', 'Turnos')},
        ),
        migrations.AlterUniqueTogether(
            name='turnos_afecta',
            unique_together={('Afecta', 'Turnos')},
        ),
        migrations.AlterUniqueTogether(
            name='evento_afecta',
            unique_together={('Afecta', 'Evento')},
        ),
    ]
