# Generated by Django 3.1.2 on 2020-10-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0004_auto_20201009_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.FileField(upload_to='')),
            ],
        ),
    ]
