# Generated by Django 3.1.2 on 2020-10-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0005_archivobd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivobd',
            name='datos',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
