# Generated by Django 3.0.7 on 2020-10-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monyLifeApp', '0005_auto_20201008_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoAfect', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEvento', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Frecuencia', models.IntegerField()),
                ('Probabilidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoRequisito', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Evento')),
                ('Requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Requisitos')),
            ],
            options={
                'unique_together': {('Requisito', 'Evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='Requisitos',
            field=models.ManyToManyField(through='monyLifeApp.Evento_Requisitos', to='monyLifeApp.Requisitos'),
        ),
        migrations.AddField(
            model_name='evento',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
    ]
