# Generated by Django 3.1.2 on 2020-10-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0006_auto_20201011_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivobd',
            old_name='datos',
            new_name='archivo',
        ),
    ]
