# Generated by Django 3.1.2 on 2020-10-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0007_auto_20201011_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivoBD',
            new_name='Files',
        ),
    ]
