# Generated by Django 3.1.2 on 2020-10-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0008_auto_20201011_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='Archivos',
        ),
        migrations.AlterModelOptions(
            name='archivos',
            options={'verbose_name_plural': 'Archivos'},
        ),
        migrations.RenameField(
            model_name='archivos',
            old_name='archivo',
            new_name='Archivo',
        ),
    ]
