# Generated by Django 3.0.7 on 2020-10-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0008_auto_20201008_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Afecta',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='Requisitos',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='User',
        ),
        migrations.AlterUniqueTogether(
            name='evento_afecta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evento_afecta',
            name='Afecta',
        ),
        migrations.RemoveField(
            model_name='evento_afecta',
            name='Evento',
        ),
        migrations.AlterUniqueTogether(
            name='evento_requisitos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evento_requisitos',
            name='Evento',
        ),
        migrations.RemoveField(
            model_name='evento_requisitos',
            name='Requisito',
        ),
        migrations.DeleteModel(
            name='Afecta',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Evento_Afecta',
        ),
        migrations.DeleteModel(
            name='Evento_Requisitos',
        ),
        migrations.DeleteModel(
            name='Requisitos',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
