# Generated by Django 3.1.2 on 2020-10-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0009_auto_20201011_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreInversion', models.CharField(blank=True, max_length=40, null=True)),
                ('TipoEmpresa', models.CharField(blank=True, max_length=40, null=True)),
                ('SaldoInicial', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SaldoAportacion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('TasaRendimiento', models.CharField(blank=True, max_length=40, null=True)),
                ('Aportacion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SaldoActual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Inversion',
            },
        ),
        migrations.CreateModel(
            name='Inversion_Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=40, null=True)),
                ('Duracion', models.IntegerField()),
                ('Afecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.afecta')),
                ('Inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.inversion')),
                ('Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.periodo')),
            ],
            options={
                'verbose_name_plural': 'Inversion Afecta',
                'unique_together': {('Afecta', 'Inversion')},
            },
        ),
        migrations.CreateModel(
            name='TipoInversiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inversion', models.CharField(blank=True, max_length=40, null=True)),
                ('TipoInversion', models.CharField(blank=True, max_length=40, null=True)),
                ('RangoRendimiento', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo Inversion',
            },
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Cantidad',
            new_name='CantidadPrestada',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='Intereses',
            new_name='Interes',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='Requisitos',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='Prestamo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='AbonoCapital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Amortizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Enganche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Mensualidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='SaldoAbsoluto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='ValorTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tipopregunta',
            name='SaldoInversion',
            field=models.CharField(default=0, max_length=30, verbose_name='Saldo de Inversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipopregunta',
            name='TasaRendimiento',
            field=models.CharField(default=0, max_length=30, verbose_name='Tasa de Rendimiento'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Prestamo_Requisitos',
        ),
        migrations.AddField(
            model_name='inversion',
            name='Afecta',
            field=models.ManyToManyField(through='monyLifeApp.Inversion_Afecta', to='monyLifeApp.Afecta'),
        ),
        migrations.AddField(
            model_name='inversion',
            name='TipoInversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.tipoinversiones'),
        ),
        migrations.AddField(
            model_name='inversion',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.user'),
        ),
    ]
