# Generated by Django 3.1.2 on 2020-11-07 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monyLifeApp', '0011_auto_20201103_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='User',
        ),
        migrations.CreateModel(
            name='Evento_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frecuencia', models.IntegerField()),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.evento')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evento_User',
                'unique_together': {('User', 'Evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='User',
            field=models.ManyToManyField(through='monyLifeApp.Evento_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
