# Generated by Django 3.0.7 on 2020-10-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monyLifeApp', '0011_auto_20201026_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoAfect', models.CharField(max_length=30, verbose_name='Tipo Afecta')),
            ],
            options={
                'verbose_name_plural': 'Afecta',
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Archivo', models.FileField(upload_to='Files/')),
            ],
            options={
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Frecuencia', models.IntegerField()),
                ('Probabilidad', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPeriodo', models.CharField(max_length=30)),
                ('Turnos', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Periodo',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Probabilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoRequisito', models.CharField(max_length=30, verbose_name='Tipo Requisito')),
            ],
            options={
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEvento', models.CharField(max_length=30, verbose_name='Tipo Evento')),
            ],
            options={
                'verbose_name_plural': 'Tipo Evento',
            },
        ),
        migrations.CreateModel(
            name='TipoInversiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inversion', models.CharField(blank=True, max_length=40, null=True)),
                ('TipoInversion', models.CharField(blank=True, max_length=40, null=True)),
                ('RangoRendimiento', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo Inversion',
            },
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPregunta', models.CharField(max_length=30, verbose_name='Tipo Pregunta')),
                ('TasaRendimiento', models.CharField(max_length=30, verbose_name='Tasa de Rendimiento')),
                ('SaldoInversion', models.CharField(max_length=30, verbose_name='Saldo de Inversion')),
            ],
            options={
                'verbose_name_plural': 'Tipo Pregunta',
            },
        ),
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPrestamo', models.IntegerField()),
                ('TipoPrestamo', models.CharField(max_length=30, verbose_name='Tipo Prestamo')),
                ('Duracion', models.CharField(max_length=30, verbose_name='Tipo Prestamo')),
                ('TazaInteres', models.CharField(max_length=30, verbose_name='Tipo Prestamo')),
            ],
            options={
                'verbose_name_plural': 'Tipo Prestamo',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroTurnos', models.IntegerField()),
                ('Felicidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('DineroEfectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Egresos', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RolUsuario', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Turnos_Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Requisitos')),
                ('Turnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Turnos')),
            ],
            options={
                'verbose_name_plural': 'Turno_Requisito',
                'unique_together': {('Requisito', 'Turnos')},
            },
        ),
        migrations.CreateModel(
            name='Turnos_Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Afecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Afecta')),
                ('Turnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Turnos')),
            ],
            options={
                'verbose_name_plural': 'Turno_Requisito',
                'unique_together': {('Afecta', 'Turnos')},
            },
        ),
        migrations.AddField(
            model_name='turnos',
            name='Afecta',
            field=models.ManyToManyField(through='monyLifeApp.Turnos_Afecta', to='monyLifeApp.Afecta'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='Evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Evento'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='Preguntas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Preguntas'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='Requisitos',
            field=models.ManyToManyField(through='monyLifeApp.Turnos_Requisitos', to='monyLifeApp.Requisitos'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
        migrations.CreateModel(
            name='TipoPrestamo_Afect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=40, null=True)),
                ('Duracion', models.IntegerField()),
                ('Afecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Afecta')),
                ('Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Periodo')),
                ('TipoPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.TipoPrestamo')),
            ],
            options={
                'verbose_name_plural': 'Prestamo_Afecta',
                'unique_together': {('Afecta', 'TipoPrestamo')},
            },
        ),
        migrations.AddField(
            model_name='tipoprestamo',
            name='Afecta',
            field=models.ManyToManyField(through='monyLifeApp.TipoPrestamo_Afect', to='monyLifeApp.Afecta'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValorTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CantidadPrestada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Enganche', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Amortizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Interes', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Mensualidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('AbonoCapital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SaldoAbsoluto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User')),
                ('idPrestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.TipoPrestamo', verbose_name='Tipo Prestamo')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=40, null=True)),
                ('Preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Preguntas')),
                ('Requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Requisitos')),
            ],
            options={
                'verbose_name_plural': 'Pregunta_Requisito',
                'unique_together': {('Requisito', 'Preguntas')},
            },
        ),
        migrations.CreateModel(
            name='Preguntas_Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=40, null=True)),
                ('Duracion', models.IntegerField()),
                ('Afecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Afecta')),
                ('Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Periodo')),
                ('Preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Preguntas')),
            ],
            options={
                'verbose_name_plural': 'Pregunta_Afecta',
                'unique_together': {('Afecta', 'Preguntas')},
            },
        ),
        migrations.AddField(
            model_name='preguntas',
            name='Afecta',
            field=models.ManyToManyField(through='monyLifeApp.Preguntas_Afecta', to='monyLifeApp.Afecta'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='Requisitos',
            field=models.ManyToManyField(through='monyLifeApp.Preguntas_Requisitos', to='monyLifeApp.Requisitos'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='TipoPreguntas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.TipoPregunta', verbose_name='Tipo Pregunta'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
        migrations.CreateModel(
            name='InversionPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaldoInicial', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('InicialMasAportacion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('EventoExterno', models.CharField(max_length=30)),
                ('TazaRendimiento', models.CharField(max_length=30)),
                ('Aportacion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SaldoActual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SaldoInvercion', models.CharField(max_length=30)),
                ('TipoInversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.TipoPregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreInversion', models.CharField(blank=True, max_length=40, null=True)),
                ('TipoEmpresa', models.CharField(blank=True, max_length=40, null=True)),
                ('SaldoInicial', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SaldoAportacion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('EventoExterno', models.CharField(blank=True, max_length=40, null=True)),
                ('TasaRendimiento', models.CharField(blank=True, max_length=40, null=True)),
                ('Aportacion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SaldoActual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('TipoInversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.TipoInversiones')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User')),
            ],
            options={
                'verbose_name_plural': 'Inversion',
            },
        ),
        migrations.CreateModel(
            name='Evento_Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=40, null=True)),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Evento')),
                ('Requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Requisitos')),
            ],
            options={
                'verbose_name_plural': 'Evento_Requisito',
                'unique_together': {('Requisito', 'Evento')},
            },
        ),
        migrations.CreateModel(
            name='Evento_Afecta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.CharField(blank=True, max_length=40, null=True)),
                ('Duracion', models.IntegerField()),
                ('Afecta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Afecta')),
                ('Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Evento')),
                ('Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.Periodo')),
            ],
            options={
                'verbose_name_plural': 'Evento_Afecta',
                'unique_together': {('Afecta', 'Evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='Afecta',
            field=models.ManyToManyField(through='monyLifeApp.Evento_Afecta', to='monyLifeApp.Afecta'),
        ),
        migrations.AddField(
            model_name='evento',
            name='Requisitos',
            field=models.ManyToManyField(through='monyLifeApp.Evento_Requisitos', to='monyLifeApp.Requisitos'),
        ),
        migrations.AddField(
            model_name='evento',
            name='TipoEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.TipoEvento', verbose_name='Tipo Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monyLifeApp.User'),
        ),
    ]
