# Generated by Django 3.1.2 on 2020-11-08 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monyLifeApp', '0012_auto_20201107_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='Afecta',
            field=models.ManyToManyField(null=True, through='monyLifeApp.Turnos_Afecta', to='monyLifeApp.Afecta'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='Evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.evento'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='Preguntas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monyLifeApp.preguntas'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='Requisitos',
            field=models.ManyToManyField(null=True, through='monyLifeApp.Turnos_Requisitos', to='monyLifeApp.Requisitos'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='Sexo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
